# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=120)),
                ('hint', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
