# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usermodel_institute'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='Profile',
        ),
    ]
