# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180113_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
